extends:
  - stylelint-high-performance-animation
  - stylelint-order
  - stylelint-declaration-block-no-ignored-properties
  - stylelint-config-standard-vue
  - stylelint-config-idiomatic-order
plugins:
  - stylelint-scss
  - stylelint-prettier
  - stylelint-order
rules:
  property-no-vendor-prefix:
    - true
    - ignoreProperties: [backdrop-filter]
  color-hex-length: long
  prettier/prettier: true
