allowBuilds:
  "@sentry/cli": false
  esbuild: false
minimumReleaseAgeExclude:
  - "@types/node@25.9.0"
  - "@typescript-eslint/eslint-plugin@8.59.4"
  - "@typescript-eslint/parser@8.59.4"
  - "@typescript-eslint/project-service@8.59.4"
  - "@typescript-eslint/scope-manager@8.59.4"
  - "@typescript-eslint/tsconfig-utils@8.59.4"
  - "@typescript-eslint/type-utils@8.59.4"
  - "@typescript-eslint/types@8.59.4"
  - "@typescript-eslint/typescript-estree@8.59.4"
  - "@typescript-eslint/utils@8.59.4"
  - "@typescript-eslint/visitor-keys@8.59.4"
  - "@vue/language-core@3.3.0"
  - date-fns@4.2.1
  - tsx@4.22.2
  - typescript-eslint@8.59.4
  - vue-tsc@3.3.0
  - "@types/node@25.9.1"
  - "@vue/language-core@3.3.1"
  - echarts@6.1.0
  - tsx@4.22.3
  - vue-tsc@3.3.1
  - "@pkgr/core@0.3.6"
  - concurrently@10.0.0
  - eslint-plugin-prettier@5.5.6
  - swiper@12.2.0
  - synckit@0.11.13
