name: 非预期错误和漏洞
description: 提交非预期错误和漏洞
title: "[Bug] "
labels:
  - BUG
  - Question
body:
  - type: markdown
    attributes:
      value: |
        在此填写非预期错误和漏洞的详细信息，包括但不限于：
        - 你所遇到的问题
        - 当前使用版本
        - 复现流程
  - type: input
    id: version
    attributes:
      label: 当前使用版本
      description: 请填写当前使用版本
      placeholder: 如 Beta v0.9.1，**如果是微软应用商店下载的请注明**
    validations:
      required: true
  - type: checkboxes
    attributes:
      label: Issue Check
      options:
        - label: 我确认查找过相关的 Issue
          required: false
        - label: 我确认这个问题是影响使用的
          required: false
        - label: 我阅读过[提问的艺术](https://github.com/betaseeker/How-To-Ask-Questions)
          required: false
  - type: textarea
    id: description
    attributes:
      label: 问题描述
      description: 请详细描述你所遇到的问题
      placeholder: 请详细描述你所遇到的问题
    validations:
      required: true
  - type: textarea
    id: reproduce
    attributes:
      label: 复现流程
      description: 请详细描述复现流程
      placeholder: 若无法复现，请填写无法复现
    validations:
      required: true
  - type: textarea
    id: additional
    attributes:
      label: 其他信息
      description: 请填写其他信息
      placeholder: 请填写其他信息
    validations:
      required: false
